import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Task from "./components/Task";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [formShow, setFormShow] = useState<string>('');
  return (
    <>
      <Head>
        <title>Trello App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
		     <div className="flex-item">

         

<div className="container-fluid">
        <div className="container ">
          <div className="row">
            
          <Task title="todo" formShow={formShow} setFormShow={setFormShow} />
					<Task title="doing" formShow={formShow} setFormShow={setFormShow} />
					<Task title="done" formShow={formShow} setFormShow={setFormShow} />


          </div>
        </div>
      </div>
         </div>
     </main>
    </>
  );
}
